site_name: ml4cps
site_url: https://ml4cps.ai4cps.com
repo_url: https://github.com/ai4cps-com/ml4cps
repo_name: ai4cps-com/ml4cps

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - fenced_code
  - tables
  - toc:
      permalink: true